### PR TITLE
Add Nuget package option for scanning projects on build.

### PR DESCRIPTION
**Pull request by nazgul26**
This change allows people to use Nuget Auditor during the build process.  This allows scanning to take place as part of a CI process.  If you need additional information or document please let me know.  I am sure others could find this helpful to their process.

### CODE REVIEW

**Comment by ken-duck** [comment]
This is great! I think it is a great idea and am definitely keen.

In order to directly use your contribution Sonatype requests that you sign a CLA (Contributor License Agreement) which more or less grants Sonatype permission to use the code. The agreement is reasonably short.

http://www.sonatype.org/SonatypeCLA.pdf

If you are alright with this, you can send the signed document here: jhesse@sonatype.com

If you could then notify me that would be great, since I will probably not be informed directly.

**Comment by nazgul26** [comment]
The URL redirects to main site instead of giving me the PDF.  I am fine signing it.  Just need to get the PDF.

**Comment by ken-duck** [comment]
Ya. As of just a few days ago the website was restructured, and the PDF has not made it back on the site yet. I am working with the folks involved to hopefully get the document put back up soon (or for them to send me a copy to post you). I will write back as soon as I get more information.

**Comment by ken-duck** [comment]
Alright, it looks like it will take a bit longer before the CLA gets online. I think they are making a more automated system that will make signing and management easier, but this may take more time to develop.

So meanwhile I am attaching a PDF of the document. Once signed you can send the signed document here ( jhesse@sonatype.com ) and then notify me since I will probably not be informed directly.

[SonatypeCLA.pdf](https://github.com/OSSIndex/audit.net/files/1866593/SonatypeCLA.pdf)

**Comment by ken-duck** [comment]
Oops. Had to revert. We don't have a signed CLA.

**Pull request merged**
